# Generated by Django 5.1.7 on 2025-05-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='ipfs_hash',
            field=models.CharField(blank=True, help_text='InterPlanetary File System Block ID', max_length=255, null=True),
        ),
    ]
