# Generated by Django 5.1.7 on 2025-05-30 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_APP', '0002_property_ipfs_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=datetime.datetime(2025, 5, 30, 21, 16, 57, 941524, tzinfo=datetime.timezone.utc), help_text='Enter Your Auth Token', max_length=200),
            preserve_default=False,
        ),
    ]
